// Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fleet

import (
	"bytes"
	"fmt"
	"os"
	"path"

	"gopkg.in/yaml.v3"

	"github.com/NVIDIA/aicr/pkg/bundler/deployer"
	"github.com/NVIDIA/aicr/pkg/bundler/deployer/localformat"
	"github.com/NVIDIA/aicr/pkg/errors"
	"github.com/NVIDIA/aicr/pkg/recipe"
)

const fileHelmOps = "helmops.yaml"

// HelmOp is the fleet.cattle.io/v1alpha1 HelmOp emitted in ModeHelmOp. Fleet
// pulls the chart from its repository at deploy time instead of embedding it
// in a Bundle, so large charts stay under the API server's request limit.
type HelmOp struct {
	APIVersion string         `yaml:"apiVersion"`
	Kind       string         `yaml:"kind"`
	Metadata   HelmOpMetadata `yaml:"metadata"`
	Spec       HelmOpSpec     `yaml:"spec"`
}

// HelmOpMetadata is the metadata subset a HelmOp needs.
type HelmOpMetadata struct {
	Name      string            `yaml:"name"`
	Namespace string            `yaml:"namespace"`
	Labels    map[string]string `yaml:"labels,omitempty"`
}

// HelmOpSpec is the HelmOp spec subset this deployer emits. The field shape
// matches what the SUSE AI Factory operator writes, so both coexist cleanly.
type HelmOpSpec struct {
	DefaultNamespace string            `yaml:"defaultNamespace,omitempty"`
	Helm             HelmOpHelm        `yaml:"helm"`
	DependsOn        []DependsOn       `yaml:"dependsOn,omitempty"`
	Targets          []Target          `yaml:"targets"`
	Labels           map[string]string `yaml:"labels,omitempty"`
}

// HelmOpHelm is the HelmOp helm block. Values are inlined: a HelmOp has no
// Git checkout to read values files from.
type HelmOpHelm struct {
	ReleaseName       string         `yaml:"releaseName"`
	Repo              string         `yaml:"repo"`
	Chart             string         `yaml:"chart,omitempty"`
	Version           string         `yaml:"version,omitempty"`
	Values            map[string]any `yaml:"values,omitempty"`
	DisablePreProcess bool           `yaml:"disablePreProcess,omitempty"`
}

// writeHelmOpLayout writes every folder's HelmOp, in install order, to a
// single helmops.yaml. Local-chart folders have no chart repository for a
// HelmOp to pull from and are rejected.
func (g *Generator) writeHelmOpLayout(outputDir string, output *deployer.Output,
	folders []localformat.Folder, docs []FleetYAML) error {

	var buf bytes.Buffer
	buf.WriteString("# Generated by AICR\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	for i, f := range folders {
		if f.Kind != localformat.KindUpstreamHelm {
			return errors.New(errors.ErrCodeInvalidRequest,
				fmt.Sprintf("%s is a local chart (raw manifests), which --fleet-mode helmop cannot deploy "+
					"because a HelmOp needs a chart repository; use --fleet-mode gitrepo", f.Dir))
		}
		values, err := mergedValues(outputDir, f, docs[i].Helm.ValuesFiles)
		if err != nil {
			return err
		}
		ho := HelmOp{
			APIVersion: "fleet.cattle.io/v1alpha1",
			Kind:       "HelmOp",
			Metadata: HelmOpMetadata{
				Name:      docs[i].Name,
				Namespace: g.namespace(),
				Labels:    docs[i].Labels,
			},
			Spec: HelmOpSpec{
				DefaultNamespace: docs[i].DefaultNamespace,
				Helm: HelmOpHelm{
					ReleaseName:       docs[i].Helm.ReleaseName,
					Repo:              docs[i].Helm.Repo,
					Chart:             docs[i].Helm.Chart,
					Version:           docs[i].Helm.Version,
					Values:            values,
					DisablePreProcess: docs[i].Helm.DisablePreProcess,
				},
				DependsOn: docs[i].DependsOn,
				Targets:   g.targets(),
				Labels:    docs[i].Labels,
			},
		}
		if err := enc.Encode(ho); err != nil {
			return errors.Wrap(errors.ErrCodeInternal, fmt.Sprintf("encode HelmOp %s", ho.Metadata.Name), err)
		}
		output.Releases[i].Manifest = fileHelmOps
	}
	if err := enc.Close(); err != nil {
		return errors.Wrap(errors.ErrCodeInternal, "close helmops.yaml encoder", err)
	}
	if err := writeFile(outputDir, fileHelmOps, buf.Bytes()); err != nil {
		return err
	}
	output.Entrypoint = fileHelmOps
	return addFile(output, outputDir, fileHelmOps)
}

// localChartComponents lists the components localformat would write as (or
// with) a local chart: kustomize or manifest-only components, and Helm
// components carrying pre- or post-phase raw manifests.
func localChartComponents(refs []recipe.ComponentRef, pre, post map[string]map[string][]byte) []string {
	var out []string
	for _, ref := range refs {
		if ref.Type != recipe.ComponentTypeHelm || ref.Source == "" || ref.Tag != "" || ref.Path != "" ||
			len(pre[ref.Name]) > 0 || len(post[ref.Name]) > 0 {

			out = append(out, ref.Name)
		}
	}
	return out
}

// mergedValues reads f's values files in order and deep-merges them, later
// files winning, the same precedence helm applies to repeated --values.
func mergedValues(outputDir string, f localformat.Folder, valuesFiles []string) (map[string]any, error) {
	merged := map[string]any{}
	for _, name := range valuesFiles {
		rel := path.Join(f.Dir, name)
		abs, err := deployer.SafeJoin(outputDir, rel)
		if err != nil {
			return nil, err
		}
		data, err := os.ReadFile(abs)
		if err != nil {
			return nil, errors.Wrap(errors.ErrCodeInternal, fmt.Sprintf("read %s", rel), err)
		}
		var doc map[string]any
		if err := yaml.Unmarshal(data, &doc); err != nil {
			return nil, errors.Wrap(errors.ErrCodeInternal, fmt.Sprintf("parse %s", rel), err)
		}
		merged = deepMerge(merged, doc)
	}
	return merged, nil
}

func deepMerge(dst, src map[string]any) map[string]any {
	for k, v := range src {
		if sv, ok := v.(map[string]any); ok {
			if dv, ok := dst[k].(map[string]any); ok {
				dst[k] = deepMerge(dv, sv)
				continue
			}
		}
		dst[k] = v
	}
	return dst
}
